USE [master]
GO

/****** Object:  Database [RafChat]    Script Date: 5/22/2019 5:02:17 PM ******/
CREATE DATABASE [RafChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RafChat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RafChat.mdf' , SIZE = 2240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RafChat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RafChat_log.ldf' , SIZE = 560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RafChat] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RafChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RafChat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RafChat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RafChat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RafChat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RafChat] SET ARITHABORT OFF 
GO

ALTER DATABASE [RafChat] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RafChat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RafChat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RafChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RafChat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RafChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RafChat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RafChat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RafChat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RafChat] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RafChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RafChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RafChat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RafChat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RafChat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RafChat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RafChat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RafChat] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RafChat] SET  MULTI_USER 
GO

ALTER DATABASE [RafChat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RafChat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RafChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RafChat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RafChat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RafChat] SET  READ_WRITE 
GO

